update and verify application onboarding
stakater/saap-docs pull request #25
Opened 2023-05-03 13:26 UTC by mustafaStakater

2023-05-03 14:46 UTC, karl-johan-grahn requested changes

2023-05-05 06:14 UTC, mustafaStakater commented on content/for-developers/onboarding/application-onboarding.md
>  ## Junkyard
this will be a seprate section for pipelines

2023-05-05 07:12 UTC, karl-johan-grahn commented on content/for-developers/onboarding/application-onboarding.md
>  ## Junkyard
Not sure I understand, "Junkyard" will be a separate section?

2023-05-09 06:11 UTC, AsfaMumtaz submitted a review, later dismissed

2023-05-11 07:05 UTC, karl-johan-grahn commented on content/for-developers/onboarding/application-onboarding.md
>  ## Junkyard
@mustafaStakater

2023-05-11 07:10 UTC, karl-johan-grahn submitted a review, later dismissed

2023-05-11 07:20 UTC, karl-johan-grahn approved these changes

2023-05-11 07:20 UTC, merged